AllCops:
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
    - 'bin/*'

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Layout/EndAlignment:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false
